version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'my_dinner_api_db'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    restart: always
    volumes:
      - ./db_django:/var/lib/mysql
  web:
    build: .
    command: >
      bash -c "./wait-for-it.sh db:3306
      && python manage.py migrate 
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/my_dinner_api
    ports:
      - "8000:8000"
    depends_on:
      - db
