# Generated by Django 3.1.1 on 2021-12-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_dinner_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='platillo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
